name: FrankieBot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Print OS information
      run: echo "Checking compatibility on ${{ matrix.os }}"
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

  additional_steps:
    needs: build
    runs-on: ${{ matrix.os }}

    steps:
    - name: Print OS information
      run: echo "Running additional steps on ${{ matrix.os }}"
    - name: Additional steps based on OS
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          echo "Running additional steps for Windows."
          # Add Windows-specific commands here
        elif [ "${{ matrix.os }}" == "macOS-latest" ]; then
          echo "Running additional steps for macOS."
          # Add macOS-specific commands here
        else
          echo "Running additional steps for Linux."
          # Add Linux-specific commands here
        fi
